language: node_js
node_js: 'lts/*'
cache:
  directories:
    - $HOME/.npm
install:
  - npm install -g npm
  - npm ci
script:
  - make checkformatting
  - make lint
  - npm test
  - make SETTINGS_FILE=settings/chrome-prod.json dist/$(date +'%Y%m%d')-chrome-prod.zip
  - make SETTINGS_FILE=settings/chrome-qa.json dist/$(date +'%Y%m%d')-chrome-qa.zip
  - make SETTINGS_FILE=settings/firefox-prod.json dist/$(date +'%Y%m%d')-firefox-prod.xpi
  - make SETTINGS_FILE=settings/firefox-qa.json dist/$(date +'%Y%m%d')-firefox-qa.xpi
addons:
  artifacts:
    paths:
      # Upload all built extension packages
      - $(ls dist/*.zip dist/*.xpi | tr "\n" ":")
