language: node_js
node_js: 'lts/*'
install:
  - npm ci
script:
  - make checkformatting lint test
  - make SETTINGS_FILE=settings/chrome-prod.json dist/chrome-prod.zip
  - make SETTINGS_FILE=settings/chrome-qa.json dist/chrome-qa.zip
  - make SETTINGS_FILE=settings/firefox-prod.json dist/firefox-prod.xpi
  - make SETTINGS_FILE=settings/firefox-qa.json dist/firefox-qa.xpi
